apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-projects-storage
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/tabit/projects/tabit/k8s-kafka-journey
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tabit-dell-001
