apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-projects-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: dev-projects-storage