apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
  labels:
    app: node-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
        - name: node-test-main
          image: http://docker-registry.registries/lts
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      restartPolicy: Always
