apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-vscode
  labels:
    app: node-vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-vscode
  template:
    metadata:
      labels:
        app: node-vscode
    spec:
      containers:
        - name: node-vscode-main
          image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "echo Container started\ntrap \"exit 0\" 15\n\nexec \"$@\"\nwhile sleep 1 & wait $!; do :; done"
            - "-"
          volumeMounts:
            - mountPath: /home/node/projects
              name: dev-projects
      volumes:
        - name: dev-projects
          persistentVolumeClaim:
            claimName: dev-projects-storage-claim
      restartPolicy: Always
